from __future__ import annotations

from dataclasses import asdict, dataclass
from math import ceil

from .constants import BASE, PRODUCTS
from .simulator import market_price

PREMIUM = ("STRAWBERRY", "MELON", "MILK", "WOOL")


@dataclass(frozen=True)
class MarketTimingConfig:
    """Research-only controls for a market-timing overlay.

    The overlay never changes movement, farm maintenance, or production. It
    only changes the quantity/timing of premium SELL orders generated by a
    parent policy. Defaults are intentionally conservative so the exact V32
    anchor can remain the control arm in paired tournaments.
    """

    floor_ratio: float = 0.72
    max_price_drop_ratio: float = 0.10
    crowd_threshold: int = 12
    scarcity_threshold: int = 10
    front_run_min_price_ratio: float = 0.74
    scarcity_min_price_ratio: float = 1.03
    terminal_soft_steps: int = 96
    terminal_mid_steps: int = 48
    terminal_hard_steps: int = 12
    shed_soft: int = 76
    shed_hard: int = 90


DEFAULT_TIMING_CONFIG = MarketTimingConfig()


def _product(product: str) -> str:
    product = str(product).upper()
    if product not in PRODUCTS:
        raise ValueError(product)
    return product


def external_inventory_pressure(previous_inventory: int | None,
                                current_inventory: int,
                                own_last_sell: int = 0) -> int:
    """Signed net market-inventory change excluding our previous sale.

    Positive values mean net external supply pressure; negative values mean
    the market was drained by town/opponent demand. This is deliberately
    called external pressure, not opponent sales, because town consumption is
    part of the public market process and cannot be separated perfectly from
    consecutive observations.
    """

    current_inventory = int(current_inventory)
    if previous_inventory is None:
        return 0
    return current_inventory - int(previous_inventory) - max(0, int(own_last_sell))


def impact_limited_units(product: str,
                         inventory: int,
                         quantity: int,
                         floor_ratio: float = 0.72,
                         max_price_drop_ratio: float = 0.10) -> int:
    """Maximum units sellable without violating a marginal-price guard.

    Kaggriculture prices are deterministic functions of market inventory, so
    this evaluates the exact marginal price path of our own order. The guard
    is expressed relative to product base price, making tuning comparable
    across premium products.
    """

    product = _product(product)
    quantity = max(0, int(quantity))
    inventory = int(inventory)
    if quantity == 0:
        return 0

    base = float(BASE[product])
    floor = max(1.0, float(floor_ratio) * base)
    max_drop = max(0.0, float(max_price_drop_ratio)) * base
    start_price = float(market_price(product, inventory))
    accepted = 0

    for i in range(quantity):
        inv = inventory + i
        quote = float(market_price(product, inv))
        after = float(market_price(product, inv + 1))
        if quote < floor:
            break
        if max_drop > 0 and start_price - after > max_drop:
            break
        accepted += 1
    return accepted


def minimum_terminal_release(quantity: int,
                             remaining_steps: int,
                             config: MarketTimingConfig = DEFAULT_TIMING_CONFIG) -> int:
    """Progressively unwind inventory instead of waiting for a final dump."""

    quantity = max(0, int(quantity))
    remaining_steps = max(0, int(remaining_steps))
    if quantity == 0:
        return 0
    if remaining_steps <= config.terminal_hard_steps:
        return quantity
    if remaining_steps <= config.terminal_mid_steps:
        return max(1, ceil(quantity * 0.50))
    if remaining_steps <= config.terminal_soft_steps:
        return max(1, ceil(quantity * 0.25))
    return 0


def timing_signal(product: str,
                  current_inventory: int,
                  previous_inventory: int | None,
                  own_last_sell: int,
                  config: MarketTimingConfig = DEFAULT_TIMING_CONFIG) -> dict:
    """Classify the current premium market regime from public state only."""

    product = _product(product)
    price = float(market_price(product, int(current_inventory)))
    price_ratio = price / float(BASE[product])
    pressure = external_inventory_pressure(previous_inventory, current_inventory, own_last_sell)

    crowd = (
        config.crowd_threshold > 0
        and pressure >= config.crowd_threshold
        and price_ratio >= config.front_run_min_price_ratio
    )
    scarcity = (
        config.scarcity_threshold > 0
        and pressure <= -config.scarcity_threshold
        and price_ratio >= config.scarcity_min_price_ratio
    )
    return {
        "product": product,
        "price": price,
        "price_ratio": price_ratio,
        "external_pressure": int(pressure),
        "crowd_front_run": bool(crowd),
        "scarcity_harvest": bool(scarcity),
    }


def decide_sale_units(product: str,
                      current_inventory: int,
                      previous_inventory: int | None,
                      own_last_sell: int,
                      proposed_units: int,
                      available_units: int,
                      remaining_steps: int,
                      shed_load: int,
                      config: MarketTimingConfig = DEFAULT_TIMING_CONFIG) -> dict:
    """Return a research decision for a premium SELL order.

    Neutral states use the exact impact guard. Strong crowd/scarcity signals
    may accelerate the sale up to available inventory. Shed pressure and the
    terminal horizon override timing experiments so inventory safety wins.
    """

    product = _product(product)
    proposed_units = max(0, int(proposed_units))
    available_units = max(0, int(available_units))
    quantity = min(max(proposed_units, 0), available_units)
    remaining_steps = max(0, int(remaining_steps))
    shed_load = max(0, int(shed_load))

    signal = timing_signal(
        product,
        current_inventory=current_inventory,
        previous_inventory=previous_inventory,
        own_last_sell=own_last_sell,
        config=config,
    )

    allowed = impact_limited_units(
        product,
        inventory=current_inventory,
        quantity=quantity,
        floor_ratio=config.floor_ratio,
        max_price_drop_ratio=config.max_price_drop_ratio,
    )
    reason = "elastic_drip" if allowed < quantity else "parent_quantity"

    if signal["crowd_front_run"]:
        allowed = available_units
        reason = "crowd_front_run"
    elif signal["scarcity_harvest"]:
        allowed = available_units
        reason = "scarcity_harvest"

    terminal_min = minimum_terminal_release(available_units, remaining_steps, config)
    if terminal_min > allowed:
        allowed = terminal_min
        reason = "terminal_vwap"

    if shed_load >= config.shed_hard:
        allowed = available_units
        reason = "shed_hard_release"
    elif shed_load >= config.shed_soft and available_units:
        soft_min = max(1, ceil(available_units * 0.25))
        if soft_min > allowed:
            allowed = soft_min
            reason = "shed_soft_release"

    allowed = min(available_units, max(0, int(allowed)))
    return {
        **signal,
        "proposed_units": proposed_units,
        "available_units": available_units,
        "allowed_units": allowed,
        "remaining_steps": remaining_steps,
        "shed_load": shed_load,
        "reason": reason,
        "config": asdict(config),
    }
