#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
import argparse
import json
import math
import os
import shutil
import subprocess
import sys
import tarfile

import numpy as np
import pandas as pd

PATTERNS = {
    "soil": "kaggriculture-frontier-the-soil-remembers-rain",
    "adaptive": "adaptive-farming-strategy-for-kaggriculture",
    "score3094": "3094-score-kaggriculture",
    "v16": "v16-rc5-high-score-8c-4s-premium-market-lead",
    "ranker": "kaggriculture-rank-your-agent",
    "melon": "kaggriculture-frontier-the-moon-counts-melons",
    "strict": "25-27-strict-future-v27-midgame-meta-reset",
    "findings": "kaggriculture-findings-from-zero-to-top-meta",
}

FAMILIES = {
    "soil": ["soil"],
    "adaptive_lineage": ["adaptive", "score3094"],
    "premium": ["v16"],
    "rank_melon": ["ranker", "melon"],
    "strict_future": ["strict"],
    "findings": ["findings"],
}

PREMIUM = ["STRAWBERRY", "MELON", "MILK", "WOOL"]
HARD_PREMIUM = ["MELON", "MILK", "WOOL"]


def safe_extract(tar_path: Path, dest: Path):
    dest.mkdir(parents=True, exist_ok=True)
    mains = []
    with tarfile.open(tar_path, "r:*") as tf:
        for member in tf.getmembers():
            rel = Path(member.name)
            if rel.is_absolute() or ".." in rel.parts or not member.isfile():
                continue
            fh = tf.extractfile(member)
            if fh is None:
                continue
            out = dest / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_bytes(fh.read())
            if rel.name == "main.py":
                mains.append(out)
    return sorted(mains, key=lambda p: (len(p.relative_to(dest).parts), str(p)))[0] if mains else None


def discover(input_root: Path, work: Path):
    roots = []
    for p in input_root.rglob("submission.tar.gz"):
        s = str(p).lower()
        if "kaggriculture-code-repo" not in s and "kaggriculture_code_repo" not in s:
            roots.append(p.parent)
    for p in input_root.rglob("main.py"):
        s = str(p).lower()
        if (
            "kaggriculture-code-repo" in s
            or "kaggriculture_code_repo" in s
            or "__pycache__" in p.parts
            or "_unpacked" in p.parts
            or "submission_extract" in p.parts
        ):
            continue
        roots.append(p.parent)
    roots = list(dict.fromkeys(roots))

    agents = {}
    for key, pattern in PATTERNS.items():
        matches = [r for r in roots if pattern in str(r).lower()]
        if not matches:
            continue
        src_root = matches[0]
        dest = work / "public_agents" / key
        main = None
        archive = src_root / "submission.tar.gz"
        if archive.exists():
            try:
                main = safe_extract(archive, dest)
            except Exception as exc:
                print("extract failed", key, repr(exc))
        if main is None and (src_root / "main.py").exists():
            dest.mkdir(parents=True, exist_ok=True)
            main = dest / "main.py"
            shutil.copy2(src_root / "main.py", main)
        if main:
            agents[key] = {
                "key": key,
                "root": dest,
                "main": main,
                "archive": archive if archive.exists() else None,
                "label": src_root.name,
                "source_root": str(src_root),
            }
    return agents


def clone_repo(work: Path):
    root = work / "repo"
    if root.exists():
        return root
    r = subprocess.run(
        ["git", "clone", "--depth", "1",
         "https://github.com/sidhulyalkar/kaggriculture.git", str(root)],
        capture_output=True, text=True, timeout=120,
    )
    if r.returncode:
        raise RuntimeError("Git clone failed:\n" + r.stderr[-3000:])
    return root


def copy_tree(src: Path, dest: Path):
    dest.mkdir(parents=True, exist_ok=True)
    for p in src.rglob("*"):
        if not p.is_file() or "__pycache__" in p.parts or p.suffix == ".pyc":
            continue
        rel = p.relative_to(src)
        out = dest / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(p, out)


WRAPPER = r'''# Generated by V3.1 Soil Route Counter Lab
from pathlib import Path
import copy, importlib.util, sys

CFG=__CFG__
BASE=Path(__file__).resolve().parent
PREV={}
DEFER={}
LAST_STEP=-1

def _load():
    path=BASE/"soil_parent"/"main.py"
    sys.path.insert(0,str(path.parent))
    spec=importlib.util.spec_from_file_location("soil_parent_v31",str(path))
    mod=importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

SOIL=_load()
BASE_PRICE={"STRAWBERRY":120,"MELON":250,"MILK":160,"WOOL":200}

def _reset():
    global PREV,DEFER,LAST_STEP
    PREV={}
    DEFER={k:0 for k in BASE_PRICE}
    LAST_STEP=-1

def _state(obs):
    private=obs.get("private",{}) or {}
    shed=private.get("shed",{}) or {}
    market=obs.get("market",{}) or {}
    inv=market.get("inventory",{}) or {}
    prices=market.get("prices",{}) or {}
    return shed,inv,prices

def _premium_order(o):
    return isinstance(o,list) and len(o)>=3 and o[0]=="SELL" and o[1] in CFG["items"]

def _reorder(orders):
    mode=CFG.get("order_mode","keep")
    if mode=="premium_front":
        return sorted(orders,key=lambda o:0 if _premium_order(o) else 1)
    if mode=="premium_back":
        return sorted(orders,key=lambda o:1 if _premium_order(o) else 0)
    return orders

def agent(obs,config=None):
    global PREV,DEFER,LAST_STEP
    step=int(obs.get("step",0))
    if step==0 or step<=LAST_STEP:
        _reset()
    LAST_STEP=step

    action=copy.deepcopy(SOIL.agent(obs,config))
    market=list(action.get("market",[]) or [])
    shed,inv,prices=_state(obs)
    shed_total=sum(int(v or 0) for v in shed.values())

    delta={k:int(inv.get(k,10000))-int(PREV.get(k,inv.get(k,10000))) for k in CFG["items"]}
    PREV={k:int(inv.get(k,10000)) for k in CFG["items"]}

    out=[]
    terminal=step>=int(CFG["terminal_step"])
    pressure=shed_total>=int(CFG["shed_hard"])

    for o in market:
        if not _premium_order(o):
            out.append(o)
            continue
        item=o[1]
        try:q=max(0,int(o[2]))
        except Exception:
            out.append(o)
            continue

        shock=(delta.get(item,0)>=int(CFG["shock_threshold"])) if CFG["shock_threshold"]>0 else False
        price=float(prices.get(item,BASE_PRICE[item]))
        low=(price < BASE_PRICE[item]*float(CFG["price_ratio"])) if CFG["price_ratio"]>0 else False
        in_window=int(CFG["start_step"])<=step<int(CFG["terminal_step"])
        guard=in_window and not terminal and not pressure and (shock or low)

        if guard:
            DEFER[item]=int(DEFER.get(item,0))+q
            continue

        if DEFER.get(item,0):
            q += int(DEFER[item])
            DEFER[item]=0
        out.append(["SELL",item,q])

    if terminal and len(out)<10:
        present={o[1] for o in out if isinstance(o,list) and len(o)>=3 and o[0]=="SELL"}
        for item in CFG["items"]:
            if len(out)>=10:break
            if item in present:continue
            q=int(shed.get(item,0) or 0)
            if q>0 and DEFER.get(item,0):
                out.append(["SELL",item,q])
                DEFER[item]=0

    action["market"]=_reorder(out)[:10]
    return action
'''


def configs():
    cfgs = {
        "pure_soil": dict(
            shock_threshold=0, price_ratio=0.0, items=PREMIUM,
            start_step=0, terminal_step=0, shed_hard=101, order_mode="keep"
        ),
    }
    for mode in ["premium_front", "premium_back"]:
        cfgs[f"order_{mode}"] = dict(
            shock_threshold=0, price_ratio=0.0, items=PREMIUM,
            start_step=144, terminal_step=696, shed_hard=90, order_mode=mode
        )
    for threshold in [8, 15, 25, 40]:
        cfgs[f"shock{threshold}_premium"] = dict(
            shock_threshold=threshold, price_ratio=0.0, items=PREMIUM,
            start_step=144, terminal_step=696, shed_hard=88, order_mode="keep"
        )
        cfgs[f"shock{threshold}_hardpremium"] = dict(
            shock_threshold=threshold, price_ratio=0.0, items=HARD_PREMIUM,
            start_step=144, terminal_step=696, shed_hard=88, order_mode="keep"
        )
    for ratio in [0.55, 0.65, 0.75]:
        cfgs[f"price{int(ratio*100)}_premium"] = dict(
            shock_threshold=0, price_ratio=ratio, items=PREMIUM,
            start_step=144, terminal_step=696, shed_hard=88, order_mode="keep"
        )
    for threshold, ratio in [(8,0.55),(15,0.55),(15,0.65),(25,0.65)]:
        cfgs[f"shock{threshold}_price{int(ratio*100)}"] = dict(
            shock_threshold=threshold, price_ratio=ratio, items=PREMIUM,
            start_step=144, terminal_step=696, shed_hard=88, order_mode="keep"
        )
    for start_day in [10, 15, 20]:
        cfgs[f"shock15_from_d{start_day}"] = dict(
            shock_threshold=15, price_ratio=0.0, items=PREMIUM,
            start_step=start_day*24, terminal_step=696,
            shed_hard=88, order_mode="keep"
        )
    return cfgs


def make_candidate(work: Path, soil, name: str, cfg: dict):
    root = work / "candidates" / name
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True)
    copy_tree(soil["root"], root / "soil_parent")
    if not (root/"soil_parent"/"main.py").exists():
        shutil.copy2(soil["main"], root/"soil_parent"/"main.py")
    (root/"main.py").write_text(WRAPPER.replace("__CFG__", repr(cfg)))
    return root


WORKER = r'''
import sys,json,time,importlib.util,traceback
from pathlib import Path
cand=Path(sys.argv[1]);opp=Path(sys.argv[2]);repo=Path(sys.argv[3])
seed=int(sys.argv[4]);seat=int(sys.argv[5])
sys.path.insert(0,str(repo));sys.path.insert(0,str(repo/"src"))
from src.kagv2.simulator import Game

def load(path,label):
    sys.path.insert(0,str(path.parent))
    spec=importlib.util.spec_from_file_location(label,str(path))
    mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod)
    fn=getattr(mod,"agent",None) or getattr(mod,"main",None)
    if callable(fn):return fn
    vals=[v for k,v in vars(mod).items()
          if callable(v) and getattr(v,"__module__",None)==mod.__name__ and not k.startswith("_")]
    if vals:return vals[-1]
    raise RuntimeError("No callable agent "+str(path))

def wrap(fn,times):
    def f(obs,configuration=None):
        t=time.perf_counter()
        try:
            try:return fn(obs,configuration)
            except TypeError:return fn(obs)
        finally:times.append(time.perf_counter()-t)
    return f

try:
    ta=[];tb=[]
    a=wrap(load(cand,"cand"),ta);b=wrap(load(opp,"opp"),tb)
    agents=[a,b] if seat==0 else [b,a]
    cash=Game(seed=seed).run(agents)
    ac,bc=(cash[0],cash[1]) if seat==0 else (cash[1],cash[0])
    print(json.dumps({
        "ok":True,"error":"","cash":float(ac),"opp_cash":float(bc),
        "score":1.0 if ac>bc else .5 if ac==bc else 0.0,
        "margin":float(ac-bc),
        "mean_ms":1000*sum(ta)/max(1,len(ta)),
        "max_ms":1000*max(ta) if ta else 0.0
    }))
except BaseException as e:
    print(json.dumps({"ok":False,"error":repr(e),"traceback":traceback.format_exc()[-3000:]}))
'''


def run_match(worker, c, o, repo, seed, seat, timeout=100):
    try:
        r=subprocess.run(
            [sys.executable,str(worker),str(c),str(o),str(repo),str(seed),str(seat)],
            capture_output=True,text=True,timeout=timeout
        )
        for line in reversed(r.stdout.splitlines()):
            try:
                x=json.loads(line);x.setdefault("error","");return x
            except Exception:pass
        return {"ok":False,"error":(r.stderr or r.stdout)[-2000:]}
    except subprocess.TimeoutExpired:
        return {"ok":False,"error":"timeout"}


def parallel(jobs, worker, repo, workers):
    rows=[]
    with ThreadPoolExecutor(max_workers=workers) as ex:
        futs={
            ex.submit(run_match,worker,c,o,repo,seed,seat):meta
            for c,o,seed,seat,meta in jobs
        }
        for i,f in enumerate(as_completed(futs),1):
            rows.append({**futs[f],**f.result()})
            if i%40==0 or i==len(futs):
                print(" completed",i,"/",len(futs))
    return pd.DataFrame(rows)


def jobs_for(candidate_roots, agents, names, seeds, opponents):
    jobs=[]
    for name in names:
        for opp in opponents:
            if opp not in agents:continue
            for seed in seeds:
                for seat in (0,1):
                    jobs.append((
                        candidate_roots[name]/"main.py",agents[opp]["main"],
                        seed*10+seat,seat,
                        {"candidate":name,"opponent":opp,"seed":seed,"seat":seat}
                    ))
    return jobs


def add_families(g):
    rev={}
    for fam,members in FAMILIES.items():
        for x in members:rev[x]=fam
    g=g.copy()
    g["family"]=g.opponent.map(rev).fillna(g.opponent)
    return g


def metrics(games):
    g=add_families(games)
    ok=g[g.ok==True].copy()
    fam=(ok.groupby(["candidate","family"])
         .agg(games=("score","size"),score=("score","mean"),margin=("margin","mean"))
         .reset_index())
    rows=[]
    for cand,x in fam.groupby("candidate"):
        vals=np.sort(x.score.to_numpy(float))
        k=max(1,int(math.ceil(.4*len(vals))))
        cg=g[g.candidate==cand];good=cg[cg.ok==True]
        amap=x[x.family=="adaptive_lineage"]
        rows.append({
            "candidate":cand,
            "mean_family_score":float(vals.mean()),
            "worst_family_score":float(vals.min()),
            "lower40_cvar":float(vals[:k].mean()),
            "robust_score":float(.55*vals.mean()+.25*vals.min()+.20*vals[:k].mean()),
            "adaptive_lineage_score":float(amap.score.iloc[0]) if len(amap) else np.nan,
            "mean_margin":float(good.margin.mean()),
            "invalid_games":int((cg.ok!=True).sum()),
            "mean_ms":float(good.mean_ms.mean()),
            "max_ms":float(good.max_ms.max()),
        })
    return pd.DataFrame(rows),fam


def passive_cash(candidate_roots,names,worker,repo,work,workers):
    p=work/"passive.py"
    # IMPORTANT: write real newlines. The previous version emitted literal "\\n"
    # sequences, making passive.py invalid Python and causing every passive game to fail.
    p.write_text(
        'def agent(observation, configuration=None):\n'
        '    return {"farmer":["PASS"],"hands":[],"market":[]}\n'
    )
    jobs=[]
    for name in names:
        for seed in [85001,85002]:
            for seat in (0,1):
                jobs.append((candidate_roots[name]/"main.py",p,seed*10+seat,seat,
                             {"candidate":name,"seed":seed,"seat":seat}))
    g=parallel(jobs,worker,repo,workers)
    good=g[g.ok==True].copy()
    if good.empty or "cash" not in good.columns:
        failures=g.loc[g.ok!=True, ["candidate","error"]].head(20).to_dict(orient="records")
        raise RuntimeError(
            "All passive-baseline games failed. This is a harness failure, not an input issue. "
            f"First failures: {failures}"
        )
    missing=sorted(set(names)-set(good.candidate.unique()))
    if missing:
        print("WARNING: no successful passive baseline for:", missing)
    return (good.groupby("candidate")
            .agg(passive_cash=("cash","mean"),passive_std=("cash","std"))
            .reset_index())


def package(root: Path,out: Path):
    with tarfile.open(out,"w:gz") as tf:
        for p in root.rglob("*"):
            if p.is_file() and "__pycache__" not in p.parts and p.suffix!=".pyc":
                tf.add(p,arcname=str(p.relative_to(root)))


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--input-root",default="/kaggle/input")
    ap.add_argument("--work",default="/kaggle/working/v31_soil_counter")
    ap.add_argument("--workers",type=int,default=min(4,os.cpu_count() or 2))
    args=ap.parse_args()

    input_root=Path(args.input_root)
    work=Path(args.work);work.mkdir(parents=True,exist_ok=True)
    repo=clone_repo(work)
    commit=subprocess.run(["git","-C",str(repo),"rev-parse","HEAD"],
                          capture_output=True,text=True).stdout.strip()
    print("repo commit",commit)

    agents=discover(input_root,work)
    missing=set(PATTERNS)-set(agents)
    if missing:
        raise RuntimeError("Missing required public inputs: "+", ".join(sorted(missing)))

    cfgs=configs()
    roots={name:make_candidate(work,agents["soil"],name,cfg) for name,cfg in cfgs.items()}
    (work/"candidate_configs.json").write_text(json.dumps(cfgs,indent=2))
    print("candidates",len(roots))

    worker=work/"match_worker.py";worker.write_text(WORKER)

    screen_opps=["adaptive","soil","v16","ranker","strict","findings"]
    screen_seeds=[83001,83002,83003]
    print("Stage 1 targeted screen")
    screen_path=work/"v31_screen_games.parquet"
    if screen_path.exists():
        print("Resuming: reusing", screen_path)
        sg=pd.read_parquet(screen_path)
    else:
        sg=parallel(jobs_for(roots,agents,list(roots),screen_seeds,screen_opps),
                    worker,repo,args.workers)
        sg.to_parquet(screen_path,index=False)
    sm,sfam=metrics(sg)
    pc=passive_cash(roots,list(roots),worker,repo,work,args.workers)
    sm=sm.merge(pc,on="candidate",how="left")

    soil=sm[sm.candidate=="pure_soil"].iloc[0]
    sm["adaptive_gain"]=sm.adaptive_lineage_score-soil.adaptive_lineage_score
    sm["robust_delta"]=sm.robust_score-soil.robust_score
    sm["passive_ratio"]=sm.passive_cash/soil.passive_cash
    sm["screen_selection_score"]=(
        sm.robust_score + .30*sm.adaptive_gain
        - .20*np.maximum(0,.97-sm.passive_ratio)
    )
    sm=sm.sort_values(["screen_selection_score","robust_score"],ascending=False)
    sm.to_csv(work/"v31_screen_scores.csv",index=False)
    sfam.to_csv(work/"v31_screen_family_matrix.csv",index=False)
    print(sm.head(12).to_string(index=False))

    finalists=sm.head(7).candidate.tolist()
    if "pure_soil" not in finalists:finalists.append("pure_soil")
    finalists=list(dict.fromkeys(finalists))[:8]
    print("finalists",finalists)

    heldout_seeds=[84001,84002,84003,84004,84005,84006,84007,84008]
    heldout_opps=["soil","adaptive","score3094","v16","ranker","melon","strict","findings"]
    print("Stage 2 held-out full meta")
    heldout_path=work/"v31_heldout_games.parquet"
    if heldout_path.exists():
        print("Resuming: reusing", heldout_path)
        hg=pd.read_parquet(heldout_path)
    else:
        hg=parallel(jobs_for(roots,agents,finalists,heldout_seeds,heldout_opps),
                    worker,repo,args.workers)
        hg.to_parquet(heldout_path,index=False)
    hm,hfam=metrics(hg)
    hp=passive_cash(roots,finalists,worker,repo,work,args.workers)
    hm=hm.merge(hp,on="candidate",how="left")

    soil=hm[hm.candidate=="pure_soil"].iloc[0]
    hm["adaptive_gain"]=hm.adaptive_lineage_score-soil.adaptive_lineage_score
    hm["robust_delta"]=hm.robust_score-soil.robust_score
    hm["passive_ratio"]=hm.passive_cash/soil.passive_cash
    hm["selection_score"]=hm.robust_score+.20*hm.adaptive_gain
    hm=hm.sort_values(["selection_score","robust_score"],ascending=False)
    hm.to_csv(work/"v31_heldout_scores.csv",index=False)
    hfam.to_csv(work/"v31_family_matrix.csv",index=False)

    promoted=hm[
        (hm.candidate!="pure_soil") &
        (hm.invalid_games==0) &
        (hm.adaptive_gain>=.10) &
        (hm.robust_delta>=-.01) &
        (hm.passive_ratio>=.97)
    ].copy()

    if len(promoted):
        best=promoted.sort_values(["selection_score","robust_score"],ascending=False).iloc[0]
        chosen=best.candidate
        reason=(
            f"Counter overlay promoted: adaptive-lineage gain {best.adaptive_gain:+.3f}, "
            f"robust delta {best.robust_delta:+.3f}, passive ratio {best.passive_ratio:.3f}."
        )
    else:
        chosen="pure_soil"
        reason=(
            "No surgical market residual improved Adaptive/3094 by >=0.10 while keeping "
            "robust score within 0.01 of Soil and >=97% passive cash. Keep exact Soil."
        )

    out=work/"NEXT_SUBMIT_v31.tar.gz";package(roots[chosen],out)
    runner=hm[hm.candidate!=chosen].iloc[0].candidate if len(hm)>1 else None
    if runner:package(roots[runner],work/"RUNNER_UP_v31.tar.gz")

    manifest={
        "version":1,"repo_commit":commit,"selected_candidate":chosen,
        "selection_reason":reason,
        "selected_stats":hm[hm.candidate==chosen].iloc[0].to_dict(),
        "soil_reference":hm[hm.candidate=="pure_soil"].iloc[0].to_dict(),
        "runner_up":runner,
        "screen_seeds":screen_seeds,"heldout_seeds":heldout_seeds,
        "promotion_gate":{
            "min_adaptive_lineage_gain":.10,"min_robust_delta":-.01,
            "min_passive_ratio":.97,"invalid_games":0,
        },
        "next_submission":str(out),
    }
    (work/"NEXT_SUBMIT_v31_manifest.json").write_text(
        json.dumps(manifest,indent=2,default=str)
    )
    print("\n=== V3.1 SELECTION ===")
    print(chosen);print(reason);print(out);print("\nHeld-out ranking")
    print(hm.to_string(index=False))


if __name__=="__main__":
    main()
