#!/usr/bin/env python3
from __future__ import annotations

"""V34 market-timing micro-patch tournament.

Research only. This script wraps a runtime-verified V32 anchor and changes
premium SELL timing/quantity while leaving the parent farm controller intact.
No candidate is emitted as submission-ready; a winner must still pass the
runtime contract and production packaging gates separately.
"""

from pathlib import Path
import argparse
import json
import math
import os
import shutil

import numpy as np
import pandas as pd

# The V3.1 lab already owns hardened public-agent discovery, isolated match
# workers, paired seats, and the dependency-free simulator runner.
import soil_route_counter_lab as base

PREMIUM = ("STRAWBERRY", "MELON", "MILK", "WOOL")
ADAPTIVE = {"adaptive", "score3094"}


def find_anchor(input_root: Path, explicit: str | None = None) -> Path:
    if explicit:
        p = Path(explicit)
        if p.exists():
            if p.is_dir() and (p / "main.py").exists():
                return p / "main.py"
            return p
        raise FileNotFoundError(f"anchor not found: {p}")

    scored = []
    for p in input_root.rglob("*"):
        if not p.is_file():
            continue
        low = str(p).lower()
        if p.name != "main.py" and not p.name.endswith(".tar.gz"):
            continue
        score = 0
        if "v32" in low:
            score += 12
        if "runtime_verified" in low or "runtime-verified" in low:
            score += 8
        if "premium" in low:
            score += 4
        if "next_submit_v32" in low:
            score += 5
        if "submit_v32" in low:
            score += 5
        if score:
            scored.append((score, -len(p.parts), str(p), p))
    if not scored:
        raise FileNotFoundError(
            "No V32 anchor found under --input-root. Add the notebook/dataset "
            "containing SUBMIT_V32_RUNTIME_VERIFIED.tar.gz or pass --anchor."
        )
    return sorted(scored, reverse=True)[0][-1]


def prepare_anchor(anchor: Path, work: Path):
    root = work / "anchor"
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True)

    if anchor.name.endswith(".tar.gz"):
        main = base.safe_extract(anchor, root)
        if main is None:
            raise RuntimeError(f"No main.py found in anchor archive {anchor}")
    elif anchor.name == "main.py":
        base.copy_tree(anchor.parent, root)
        main = root / "main.py"
    else:
        raise ValueError(f"unsupported anchor input: {anchor}")
    return root, main.relative_to(root)


def resolve_repo(input_root: Path, work: Path) -> Path:
    local = Path(__file__).resolve().parents[1]
    if (local / "src" / "kagv2" / "simulator.py").exists():
        return local
    for p in input_root.rglob("simulator.py"):
        if p.parent.name == "kagv2" and p.parent.parent.name == "src":
            root = p.parent.parent.parent
            if (root / "submission" / "base_controller.py").exists():
                return root
    return base.clone_repo(work)


WRAPPER = r'''# Generated by V34 Market Timing Lab. RESEARCH ONLY, not production packaging.
from pathlib import Path
import copy, importlib.util, math, sys

CFG=__CFG__
BASE=Path(__file__).resolve().parent
ANCHOR_MAIN=BASE/"anchor_parent"/__ANCHOR_MAIN__
PREV={}
OWN_LAST={}
LAST_STEP=-1
PREMIUM=("STRAWBERRY","MELON","MILK","WOOL")
BASE_PRICE={"STRAWBERRY":120,"MELON":250,"MILK":160,"WOOL":200}
from src.kagv2.simulator import market_price


def _load():
    sys.path.insert(0,str(ANCHOR_MAIN.parent))
    spec=importlib.util.spec_from_file_location("v32_anchor_parent",str(ANCHOR_MAIN))
    mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod)
    fn=getattr(mod,"agent",None) or getattr(mod,"main",None)
    if callable(fn):return fn
    vals=[v for k,v in vars(mod).items()
          if callable(v) and getattr(v,"__module__",None)==mod.__name__ and not k.startswith("_")]
    if vals:return vals[-1]
    raise RuntimeError("No callable agent in V32 anchor")

PARENT=_load()


def _reset():
    global PREV,OWN_LAST,LAST_STEP
    PREV={};OWN_LAST={};LAST_STEP=-1


def _call(obs,config):
    try:return PARENT(obs,config)
    except TypeError:return PARENT(obs)


def _pressure(item,cur):
    if item not in PREV:return 0
    return int(cur)-int(PREV[item])-int(OWN_LAST.get(item,0))


def _signal(item,cur):
    pressure=_pressure(item,cur)
    ratio=float(market_price(item,int(cur)))/BASE_PRICE[item]
    crowd=(CFG.get("crowd_threshold",0)>0 and
           pressure>=int(CFG["crowd_threshold"]) and
           ratio>=float(CFG.get("front_run_min_price_ratio",.74)))
    scarce=(CFG.get("scarcity_threshold",0)>0 and
            pressure<=-int(CFG["scarcity_threshold"]) and
            ratio>=float(CFG.get("scarcity_min_price_ratio",1.03)))
    return pressure,ratio,crowd,scarce


def _cap(item,inv,q):
    q=max(0,int(q));start=float(market_price(item,int(inv)));bp=BASE_PRICE[item]
    floor=float(CFG.get("floor_ratio",0))*bp
    maxdrop=float(CFG.get("max_price_drop_ratio",0))*bp
    n=0
    for i in range(q):
        quote=float(market_price(item,int(inv)+i))
        after=float(market_price(item,int(inv)+i+1))
        if floor>0 and quote<floor:break
        if maxdrop>0 and start-after>maxdrop:break
        n+=1
    return n


def _terminal_min(q,rem):
    q=max(0,int(q));rem=max(0,int(rem))
    if not q:return 0
    if rem<=int(CFG.get("terminal_hard_steps",12)):return q
    if rem<=int(CFG.get("terminal_mid_steps",48)):return max(1,math.ceil(q*.50))
    if rem<=int(CFG.get("terminal_soft_steps",96)):return max(1,math.ceil(q*.25))
    return 0


def _choose(item,inv,proposed,available,rem,shed_load):
    proposed=min(max(0,int(proposed)),max(0,int(available)))
    allowed=_cap(item,inv,proposed) if CFG.get("impact_guard",False) else proposed
    pressure,ratio,crowd,scarce=_signal(item,inv)
    if CFG.get("front_run",False) and crowd:allowed=available
    elif CFG.get("scarcity_harvest",False) and scarce:allowed=available
    if CFG.get("terminal_vwap",False):allowed=max(allowed,_terminal_min(available,rem))
    if shed_load>=int(CFG.get("shed_hard",90)):allowed=available
    elif shed_load>=int(CFG.get("shed_soft",76)):allowed=max(allowed,math.ceil(available*.25))
    return min(max(0,int(available)),max(0,int(allowed))),crowd,scarce


def _premium_front(orders):
    return sorted(orders,key=lambda o:0 if isinstance(o,list) and len(o)>=3 and o[0]=="SELL" and o[1] in PREMIUM else 1)


def agent(obs,config=None):
    global PREV,OWN_LAST,LAST_STEP
    step=int((obs or {}).get("step",0) or 0)
    if step==0 or step<=LAST_STEP:_reset()
    LAST_STEP=step
    action=copy.deepcopy(_call(obs,config))
    if CFG.get("mode")=="anchor" or not isinstance(action,dict):
        return action

    private=(obs or {}).get("private",{}) or {};shed=private.get("shed",{}) or {}
    market=(obs or {}).get("market",{}) or {};inv=market.get("inventory",{}) or {}
    shed_load=sum(int(v or 0) for v in shed.values())
    rem=max(0,718-step)
    original=list(action.get("market",[]) or [])
    out=[];present=set();new_last={}

    for o in original:
        if not (isinstance(o,list) and len(o)>=3 and o[0]=="SELL" and o[1] in PREMIUM):
            out.append(o);continue
        item=o[1];available=max(0,int(shed.get(item,0) or 0))
        try:q=max(0,int(o[2]))
        except Exception:
            out.append(o);continue
        n,_,_=_choose(item,int(inv.get(item,10000)),q,available,rem,shed_load)
        present.add(item)
        if n>0:
            out.append(["SELL",item,n]);new_last[item]=n

    # Strong regime signals can create an earlier premium sale even when the
    # anchor's reserve rule would otherwise wait. This is the key experiment:
    # front-run an incoming supply wave or monetize an already scarce market.
    if CFG.get("signal_add",False):
        additions=[]
        for item in PREMIUM:
            if item in present:continue
            available=max(0,int(shed.get(item,0) or 0))
            if available<=0:continue
            n,crowd,scarce=_choose(item,int(inv.get(item,10000)),0,available,rem,shed_load)
            trigger=(CFG.get("front_run",False) and crowd) or (CFG.get("scarcity_harvest",False) and scarce)
            trigger=trigger or (CFG.get("terminal_vwap",False) and _terminal_min(available,rem)>0)
            if trigger and n>0:
                additions.append(["SELL",item,n]);new_last[item]=n
        if additions:
            out=additions+out

    action["market"]=_premium_front(out)[:10]
    PREV={p:int(inv.get(p,10000)) for p in PREMIUM}
    OWN_LAST=new_last
    return action
'''


def configs():
    common=dict(
        floor_ratio=.72,max_price_drop_ratio=.10,
        crowd_threshold=12,scarcity_threshold=10,
        front_run_min_price_ratio=.74,scarcity_min_price_ratio=1.03,
        terminal_soft_steps=96,terminal_mid_steps=48,terminal_hard_steps=12,
        shed_soft=76,shed_hard=90,signal_add=False,
    )
    return {
        "anchor": {**common,"mode":"anchor"},
        "elastic_drip": {**common,"mode":"timing","impact_guard":True,
                          "front_run":False,"scarcity_harvest":False,"terminal_vwap":False},
        "front_run8": {**common,"mode":"timing","impact_guard":True,
                        "front_run":True,"crowd_threshold":8,"scarcity_harvest":False,
                        "terminal_vwap":False,"signal_add":True},
        "front_run15": {**common,"mode":"timing","impact_guard":True,
                         "front_run":True,"crowd_threshold":15,"scarcity_harvest":False,
                         "terminal_vwap":False,"signal_add":True},
        "scarcity8": {**common,"mode":"timing","impact_guard":True,
                       "front_run":False,"scarcity_harvest":True,"scarcity_threshold":8,
                       "terminal_vwap":False,"signal_add":True},
        "dual12": {**common,"mode":"timing","impact_guard":True,
                    "front_run":True,"scarcity_harvest":True,"terminal_vwap":False,
                    "signal_add":True},
        "dual8": {**common,"mode":"timing","impact_guard":True,
                   "front_run":True,"crowd_threshold":8,"scarcity_harvest":True,
                   "scarcity_threshold":8,"terminal_vwap":False,"signal_add":True},
        "terminal_vwap": {**common,"mode":"timing","impact_guard":True,
                           "front_run":False,"scarcity_harvest":False,"terminal_vwap":True,
                           "signal_add":True},
        "hybrid12": {**common,"mode":"timing","impact_guard":True,
                      "front_run":True,"scarcity_harvest":True,"terminal_vwap":True,
                      "signal_add":True},
    }


def make_candidate(work: Path, anchor_root: Path, anchor_main: Path, name: str, cfg: dict) -> Path:
    root=work/"candidates"/name
    if root.exists():shutil.rmtree(root)
    root.mkdir(parents=True)
    base.copy_tree(anchor_root,root/"anchor_parent")
    source=WRAPPER.replace("__CFG__",repr(cfg)).replace("__ANCHOR_MAIN__",repr(str(anchor_main)))
    (root/"main.py").write_text(source)
    return root


def _summary(df: pd.DataFrame, control="anchor") -> pd.DataFrame:
    keys=["opponent","seed","seat"]
    rows=[]
    ctl=df[df.candidate==control][keys+["score","margin","ok"]].rename(
        columns={"score":"control_score","margin":"control_margin","ok":"control_ok"}
    )
    for name,g in df.groupby("candidate"):
        merged=g.merge(ctl,on=keys,how="left")
        valid=merged[(merged.ok==True)&(merged.control_ok==True)].copy()  # noqa: E712
        delta=(valid.score-valid.control_score) if len(valid) else pd.Series(dtype=float)
        per_opp=valid.assign(delta=delta).groupby("opponent").delta.mean() if len(valid) else pd.Series(dtype=float)
        adaptive=valid[valid.opponent.isin(ADAPTIVE)]
        rows.append({
            "candidate":name,
            "games":int(len(g)),
            "invalid_games":int((g.ok!=True).sum()),  # noqa: E712
            "mean_score":float(pd.to_numeric(g.loc[g.ok==True,"score"],errors="coerce").mean()),  # noqa: E712
            "robust_delta":float(delta.mean()) if len(delta) else -1.0,
            "adaptive_delta":float((adaptive.score-adaptive.control_score).mean()) if len(adaptive) else 0.0,
            "worst_opponent_delta":float(per_opp.min()) if len(per_opp) else -1.0,
            "mean_margin_delta":float((valid.margin-valid.control_margin).mean()) if len(valid) else float("nan"),
        })
    out=pd.DataFrame(rows)
    out["utility"]=out.robust_delta+.75*out.adaptive_delta+.25*np.minimum(out.worst_opponent_delta,0)
    return out.sort_values(["utility","robust_delta"],ascending=False).reset_index(drop=True)


def _promotion(table: pd.DataFrame):
    candidates=table[(table.candidate!="anchor")&(table.invalid_games==0)].copy()
    passed=candidates[
        (candidates.robust_delta>=.015)&
        (candidates.adaptive_delta>=.04)&
        (candidates.worst_opponent_delta>=-.03)
    ]
    if passed.empty:
        return "anchor", "No V34 timing overlay cleared the robust promotion gate."
    r=passed.sort_values(["utility","robust_delta"],ascending=False).iloc[0]
    return str(r.candidate), (
        f"Promoted {r.candidate}: robust {r.robust_delta:+.4f}, "
        f"adaptive {r.adaptive_delta:+.4f}, worst opponent {r.worst_opponent_delta:+.4f}."
    )


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--input-root",default="/kaggle/input")
    ap.add_argument("--work",default="/kaggle/working/v34_market_timing")
    ap.add_argument("--anchor",default=None,
                    help="Optional V32 tar.gz or main.py; auto-discovered when omitted")
    ap.add_argument("--workers",type=int,default=min(4,os.cpu_count() or 2))
    args=ap.parse_args()

    input_root=Path(args.input_root);work=Path(args.work);work.mkdir(parents=True,exist_ok=True)
    anchor=find_anchor(input_root,args.anchor)
    anchor_root,anchor_main=prepare_anchor(anchor,work)
    repo=resolve_repo(input_root,work)
    agents=base.discover(input_root,work)
    if not agents:
        raise RuntimeError("No public opponent agents discovered. Attach the V3.1 public-agent Kaggle inputs.")

    cfgs=configs()
    roots={n:make_candidate(work,anchor_root,anchor_main,n,c) for n,c in cfgs.items()}
    worker=work/"worker.py";worker.write_text(base.WORKER)

    targeted=[x for x in ("adaptive","score3094","soil","v16") if x in agents]
    if len(targeted)<2:targeted=list(agents)[:min(4,len(agents))]
    screen_seeds=[3401,3407,3413,3419]
    print("V34 SCREEN",len(cfgs),"candidates",targeted,"seeds",screen_seeds)
    jobs=base.jobs_for(roots,agents,list(cfgs),screen_seeds,targeted)
    screen=base.parallel(jobs,worker,repo,args.workers)
    screen.to_csv(work/"screen_games.csv",index=False)
    screen_table=_summary(screen)
    screen_table.to_csv(work/"screen_summary.csv",index=False)
    print(screen_table.to_string(index=False))

    finalists=screen_table[(screen_table.candidate!="anchor")&(screen_table.invalid_games==0)].head(3).candidate.tolist()
    held_names=["anchor",*finalists]
    held_seeds=[3511,3527,3541,3557,3571,3581]
    held_opponents=list(agents)
    print("V34 HELDOUT",held_names,"opponents",held_opponents,"seeds",held_seeds)
    jobs=base.jobs_for(roots,agents,held_names,held_seeds,held_opponents)
    held=base.parallel(jobs,worker,repo,args.workers)
    held.to_csv(work/"heldout_games.csv",index=False)
    held_table=_summary(held)
    held_table.to_csv(work/"heldout_summary.csv",index=False)
    print(held_table.to_string(index=False))

    selected,reason=_promotion(held_table)
    decision={
        "version":34,
        "selected_candidate":selected,
        "selection_reason":reason,
        "anchor":str(anchor),
        "anchor_main":str(anchor_main),
        "screen_opponents":targeted,
        "screen_seeds":screen_seeds,
        "heldout_opponents":held_opponents,
        "heldout_seeds":held_seeds,
        "finalists":finalists,
        "promotion_gate":{
            "min_robust_delta":.015,
            "min_adaptive_delta":.04,
            "min_worst_opponent_delta":-.03,
            "invalid_games":0,
        },
        "submission_ready":False,
        "production_note":"Winning overlay must be compiled into a single-file V32 runtime and pass the runtime submission contract before upload.",
    }
    (work/"decision.json").write_text(json.dumps(decision,indent=2,sort_keys=True))
    print(json.dumps(decision,indent=2))


if __name__=="__main__":
    main()
